- name: Provision host to operate as dsp box
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - { role: configure, tags: ['configure'] }
    - { role: common, tags: ['common'] }
    - { role: hifiberry, tags: ['hifiberry'] }
    - { role: accesspoint, tags: ['accesspoint'] }
    - { role: puredata, tags: ['puredata'] }
  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted
    - name: reload systemd
      become: yes
      command: systemctl daemon-reload