- name: ensure apt repositories are installed
  apt_repository:
    repo: "{{item}}"
    state: present
    update_cache: yes
  with_items: "{{apt_repos}}"

- name: ensure apt cache is updated
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: ensure apt packages are installed
  apt:
    name: "{{item}}"
    state: latest
    force: yes
  with_items: "{{apt_packages}}"
