- name: ensure apt cache is updated
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: ensure apt packages are installed
  apt:
    name: "{{item}}"
    state: latest
  with_items: "{{apt_packages}}"
