# ensure ssh agent forwarding is on while deploying
ansible_ssh_common_args: -o ForwardAgent=yes

hostname: pidsp
wan_interface: eth0
lan_interface: wlan0
pi_ssid: WuTangLAN
wifi_password: googlybear
default_puredata_patch: "/home/{{ lookup('env', 'USER') }}/inToOutLopSecond.pd"

apt_packages:
  - vim
  - git
  - puredata
  - gem
  - pd-zexy
  - pd-aubio
  - pd-csound
  - isc-dhcp-server
  - bind9
  - hostapd
  - haveged
  - ansible

apt_repos:
  - deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main