# ensure ssh agent forwarding is on while deploying
ansible_ssh_common_args: -o ForwardAgent=yes

hostname: pidsp

apt_keys:
  - "https://www.postgresql.org/media/keys/ACCC4CF8.asc"

apt_ppas:
  - "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"

apt_packages:
  - git
  - puredata
  - gem
  - pd-zexy
  - pd-aubio
  - pd-csound

